# jekyll config file
title: OS
email: contact@maxallen.io
description: >- # this means to ignore newlines until "baseurl:"
  A Second Brain for Max Allen.
baseurl: "/OS" # the subpath of your site, e.g. /blog
url: "https://max-allen.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
theme: just-the-docs
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown